language: python
branches:
  except:
  - gh-pages
matrix:
  include:
  - python: 3.4
    env: TOXENV=unit_py3,check,doc_travis
  - python: 2.7
    env: TOXENV=unit_py2,check,doc_travis
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y git
- sudo apt-get install -y xsltproc
- sudo apt-get install -y genisoimage
- sudo apt-get install -y enchant
- sudo apt-get install -y shellcheck
install:
- pip install --upgrade pip
- pip install -r .travis.requirements.txt
script:
- tox
after_success:
- tox -e doc_travis_deploy
